-- water_Department

INSERT INTO `water_Department` VALUES (1, '三明市河长办', null, null, 1, 0, null);
INSERT INTO `water_Department` VALUES (2, '三明市水利局', 1, null, 1, 0, null );
INSERT INTO `water_Department` VALUES (3, '三明市环保局', 1, null, 1, 0, null);
INSERT INTO `water_Department` VALUES (4, '三明市住建局', 1, null, 1, 0, null);
INSERT INTO `water_Department` VALUES (5, '三明市农业局', 1, null, 1, 0, null);
INSERT INTO `water_Department` VALUES (6, '三明市经信局', 1, null, 1, 0, null);
INSERT INTO `water_Department` VALUES (7, '梅列区河长办', null, 1, 2, 0, null);
INSERT INTO `water_Department` VALUES (8, '梅列区水利局', 7, 2, 2, 0, null);
INSERT INTO `water_Department` VALUES (9, '梅列区环保局', 7, 3, 2, 0, null);
INSERT INTO `water_Department` VALUES (10, '梅列区住建局', 7, 4, 2, 0, null);
INSERT INTO `water_Department` VALUES (11, '梅列区农业局', 7, 5, 2, 0, null);
INSERT INTO `water_Department` VALUES (12, '梅列区经信局', 7, 6, 2, 0, null);

-- `water_User`
INSERT INTO `water_UserType` VALUES (1,'办公用户');
INSERT INTO `water_UserType` VALUES (2,'河道用户');
INSERT INTO `water_UserType` VALUES (999,'管理员');

INSERT INTO `water_User` VALUES (1,'管理员','admin','123456',0,null,null,now(),0,999,1);
INSERT INTO `water_User` VALUES (2,'普通用户','wyy','123456',0,null,null,now(),0,999,2);
-- water_Status

INSERT INTO `water_Status` VALUES (1, '正常', 'user');
INSERT INTO `water_Status` VALUES (2, '停权', 'user');
INSERT INTO `water_Status` VALUES (3, '待审核', 'user');
INSERT INTO `water_Status` VALUES (10, '正常', 'monitor_site');
INSERT INTO `water_Status` VALUES (11, '关停', 'monitor_site');
INSERT INTO `water_Status` VALUES (12, '重点', 'monitor_site');
INSERT INTO `water_Status` VALUES (13, '待确认', 'event');
INSERT INTO `water_Status` VALUES (14, '处理中', 'event');
INSERT INTO `water_Status` VALUES (15, '已办结', 'event');
INSERT INTO `water_Status` VALUES (21, '待接收', 'flow');
INSERT INTO `water_Status` VALUES (22, '处理中', 'flow');
INSERT INTO `water_Status` VALUES (23, '已处理', 'flow');
INSERT INTO `water_Status` VALUES (24, '退回', 'flow');
INSERT INTO `water_Status` VALUES (28, '待处理', 'checkup');
INSERT INTO `water_Status` VALUES (29, '处理中', 'checkup');
INSERT INTO `water_Status` VALUES (30, '已完成', 'checkup');
INSERT INTO `water_Status` VALUES (31, '待发布', 'article');
INSERT INTO `water_Status` VALUES (32, '已发布', 'article');
INSERT INTO `water_Status` VALUES (33, '置顶', 'article');

-- water_Role

INSERT INTO `water_Role` VALUES (1, '系统管理员','admin', 1);
INSERT INTO `water_Role` VALUES (2, '综合席','zhonghexi', 1);
INSERT INTO `water_Role` VALUES (3, '水利席','shuilixi', 1);
INSERT INTO `water_Role` VALUES (4, '环保席','huanbaoxi', 1);
INSERT INTO `water_Role` VALUES (5, '经信席','jingxinxi', 1);
INSERT INTO `water_Role` VALUES (6, '住建席','zhujianxi', 0);
INSERT INTO `water_Role` VALUES (13, '河长办','hezhangban', 1);
INSERT INTO `water_Role` VALUES (14, '乡镇河长办','xz_hezhangban', 1);
INSERT INTO `water_Role` VALUES (15, '领导小组','leader_team', 1);
INSERT INTO `water_Role` VALUES (17, '市区','cityarea', 1);
INSERT INTO `water_Role` VALUES (18, '演示账号','demo', 1);
INSERT INTO `water_Role` VALUES (19, '农业席','nongyexi', 1);

-- water_Permission
INSERT INTO `water_Permission` VALUES (1, '综合席待确认事件', 'event/city', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (2, '待处理事件', 'solveflow/index', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (3, '已处理事件', 'eventflow/suspend', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (5, '事件跟踪', 'eventflow/flow', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (6, '用户管理', 'sys/user', 1, 7 ,0);
INSERT INTO `water_Permission` VALUES (7, '角色权限', 'role/lists', 1, 7 ,0);
INSERT INTO `water_Permission` VALUES (8, '组织机构管理', 'org/lists', 1, 7 ,0);
INSERT INTO `water_Permission` VALUES (10, '巡查任务', 'checkup/index', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (11, '河流地图', 'rivermap/index', 1, 1 ,0);
INSERT INTO `water_Permission` VALUES (12, '河流信息', 'river/index', 1, 1 ,0);
INSERT INTO `water_Permission` VALUES (13, '河长信息', 'riveruser/index', 1, 9 ,0);
INSERT INTO `water_Permission` VALUES (14, '河长指派', 'event/assig', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (15, '个人中心', 'sys/set', 1, 7 ,0);
INSERT INTO `water_Permission` VALUES (16, '新闻信息', 'news/index', 1, 5 ,0);
INSERT INTO `water_Permission` VALUES (17, '企业信息', 'company/index', 1, 5 ,0);
INSERT INTO `water_Permission` VALUES (18, '河道档案', 'river/doc', 1, 1 ,0);
INSERT INTO `water_Permission` VALUES (19, '监控视频', 'river/monitor', 1, 1 ,0);
INSERT INTO `water_Permission` VALUES (20, '组织体系', 'river/organ', 1, 9 ,0);
INSERT INTO `water_Permission` VALUES (21, '领导重要指示', 'river/article', 1, 9 ,0);
INSERT INTO `water_Permission` VALUES (22, '日报表', ' eval/index', 1, 8 ,0);
INSERT INTO `water_Permission` VALUES (23, '月报表', ' eval/month', 1, 8 ,0);
INSERT INTO `water_Permission` VALUES (24, '一河一策', 'river/procmethod', 1, 4 ,0);
INSERT INTO `water_Permission` VALUES (25, '公众投诉', 'news/appeal', 1, 5 ,0);
INSERT INTO `water_Permission` VALUES (26, '河管员信息', 'riveruser/zgy', 1, 9 ,0);
INSERT INTO `water_Permission` VALUES (27, '监管对象', 'river/baseinfo', 1, 1 ,0);
INSERT INTO `water_Permission` VALUES (28, '统计报表', 'eval/statement', 1, 8 ,0);
INSERT INTO `water_Permission` VALUES (29, '通知公告', 'sys/notice', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (30, '河长巡查', 'checkup/patrol', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (31, '更新日志', ' log/logupdate', 1, 12 ,0);
INSERT INTO `water_Permission` VALUES (32, '登录日志', 'log/loginlog', 1, 12 ,0);
INSERT INTO `water_Permission` VALUES (33, '考核得分设定', 'eval/score', 1, 8 ,0);
INSERT INTO `water_Permission` VALUES (34, '预设轨迹', ' event/orbit', 1, 3 ,0);
INSERT INTO `water_Permission` VALUES (35, '考核通报', 'eval/doc', 1, 8 ,0);

-- water_Permission_Role

INSERT INTO `water_Permission_Role` VALUES (1, 1);
INSERT INTO `water_Permission_Role` VALUES (1, 2);
INSERT INTO `water_Permission_Role` VALUES (1, 14);
INSERT INTO `water_Permission_Role` VALUES (1, 15);
INSERT INTO `water_Permission_Role` VALUES (1, 17);
INSERT INTO `water_Permission_Role` VALUES (1, 18);
INSERT INTO `water_Permission_Role` VALUES (1, 19);
INSERT INTO `water_Permission_Role` VALUES (2, 1);
INSERT INTO `water_Permission_Role` VALUES (2, 2);
INSERT INTO `water_Permission_Role` VALUES (2, 3);
INSERT INTO `water_Permission_Role` VALUES (2, 4);
INSERT INTO `water_Permission_Role` VALUES (2, 5);
INSERT INTO `water_Permission_Role` VALUES (2, 6);
INSERT INTO `water_Permission_Role` VALUES (2, 13);
INSERT INTO `water_Permission_Role` VALUES (2, 14);
INSERT INTO `water_Permission_Role` VALUES (2, 15);
INSERT INTO `water_Permission_Role` VALUES (2, 17);
INSERT INTO `water_Permission_Role` VALUES (2, 18);
INSERT INTO `water_Permission_Role` VALUES (2, 19);
INSERT INTO `water_Permission_Role` VALUES (3, 1);
INSERT INTO `water_Permission_Role` VALUES (3, 2);
INSERT INTO `water_Permission_Role` VALUES (3, 3);
INSERT INTO `water_Permission_Role` VALUES (3, 4);
INSERT INTO `water_Permission_Role` VALUES (3, 5);
INSERT INTO `water_Permission_Role` VALUES (3, 6);
INSERT INTO `water_Permission_Role` VALUES (3, 13);
INSERT INTO `water_Permission_Role` VALUES (3, 14);
INSERT INTO `water_Permission_Role` VALUES (3, 15);
INSERT INTO `water_Permission_Role` VALUES (3, 17);
INSERT INTO `water_Permission_Role` VALUES (3, 18);
INSERT INTO `water_Permission_Role` VALUES (3, 19);
INSERT INTO `water_Permission_Role` VALUES (5, 1);
INSERT INTO `water_Permission_Role` VALUES (5, 2);
INSERT INTO `water_Permission_Role` VALUES (5, 13);
INSERT INTO `water_Permission_Role` VALUES (5, 14);
INSERT INTO `water_Permission_Role` VALUES (5, 15);
INSERT INTO `water_Permission_Role` VALUES (5, 17);
INSERT INTO `water_Permission_Role` VALUES (5, 18);
INSERT INTO `water_Permission_Role` VALUES (5, 19);
INSERT INTO `water_Permission_Role` VALUES (6, 1);
INSERT INTO `water_Permission_Role` VALUES (6, 2);
INSERT INTO `water_Permission_Role` VALUES (6, 14);
INSERT INTO `water_Permission_Role` VALUES (6, 15);
INSERT INTO `water_Permission_Role` VALUES (6, 17);
INSERT INTO `water_Permission_Role` VALUES (6, 19);
INSERT INTO `water_Permission_Role` VALUES (7, 1);
INSERT INTO `water_Permission_Role` VALUES (7, 2);
INSERT INTO `water_Permission_Role` VALUES (7, 15);
INSERT INTO `water_Permission_Role` VALUES (7, 17);
INSERT INTO `water_Permission_Role` VALUES (7, 19);
INSERT INTO `water_Permission_Role` VALUES (8, 1);
INSERT INTO `water_Permission_Role` VALUES (8, 2);
INSERT INTO `water_Permission_Role` VALUES (8, 15);
INSERT INTO `water_Permission_Role` VALUES (8, 17);
INSERT INTO `water_Permission_Role` VALUES (8, 19);
INSERT INTO `water_Permission_Role` VALUES (10, 1);
INSERT INTO `water_Permission_Role` VALUES (10, 2);
INSERT INTO `water_Permission_Role` VALUES (10, 14);
INSERT INTO `water_Permission_Role` VALUES (10, 15);
INSERT INTO `water_Permission_Role` VALUES (10, 17);
INSERT INTO `water_Permission_Role` VALUES (10, 18);
INSERT INTO `water_Permission_Role` VALUES (10, 19);
INSERT INTO `water_Permission_Role` VALUES (11, 1);
INSERT INTO `water_Permission_Role` VALUES (11, 2);
INSERT INTO `water_Permission_Role` VALUES (11, 6);
INSERT INTO `water_Permission_Role` VALUES (11, 15);
INSERT INTO `water_Permission_Role` VALUES (11, 17);
INSERT INTO `water_Permission_Role` VALUES (11, 18);
INSERT INTO `water_Permission_Role` VALUES (11, 19);
INSERT INTO `water_Permission_Role` VALUES (12, 1);
INSERT INTO `water_Permission_Role` VALUES (12, 2);
INSERT INTO `water_Permission_Role` VALUES (12, 6);
INSERT INTO `water_Permission_Role` VALUES (12, 14);
INSERT INTO `water_Permission_Role` VALUES (12, 15);
INSERT INTO `water_Permission_Role` VALUES (12, 17);
INSERT INTO `water_Permission_Role` VALUES (12, 18);
INSERT INTO `water_Permission_Role` VALUES (12, 19);
INSERT INTO `water_Permission_Role` VALUES (13, 1);
INSERT INTO `water_Permission_Role` VALUES (13, 2);
INSERT INTO `water_Permission_Role` VALUES (13, 13);
INSERT INTO `water_Permission_Role` VALUES (13, 14);
INSERT INTO `water_Permission_Role` VALUES (13, 15);
INSERT INTO `water_Permission_Role` VALUES (13, 17);
INSERT INTO `water_Permission_Role` VALUES (13, 18);
INSERT INTO `water_Permission_Role` VALUES (13, 19);
INSERT INTO `water_Permission_Role` VALUES (14, 4);
INSERT INTO `water_Permission_Role` VALUES (14, 17);
INSERT INTO `water_Permission_Role` VALUES (14, 18);
INSERT INTO `water_Permission_Role` VALUES (14, 19);
INSERT INTO `water_Permission_Role` VALUES (15, 1);
INSERT INTO `water_Permission_Role` VALUES (15, 2);
INSERT INTO `water_Permission_Role` VALUES (15, 14);
INSERT INTO `water_Permission_Role` VALUES (15, 15);
INSERT INTO `water_Permission_Role` VALUES (15, 17);
INSERT INTO `water_Permission_Role` VALUES (15, 18);
INSERT INTO `water_Permission_Role` VALUES (15, 19);
INSERT INTO `water_Permission_Role` VALUES (16, 1);
INSERT INTO `water_Permission_Role` VALUES (16, 2);
INSERT INTO `water_Permission_Role` VALUES (16, 15);
INSERT INTO `water_Permission_Role` VALUES (16, 17);
INSERT INTO `water_Permission_Role` VALUES (16, 18);
INSERT INTO `water_Permission_Role` VALUES (16, 19);
INSERT INTO `water_Permission_Role` VALUES (17, 1);
INSERT INTO `water_Permission_Role` VALUES (17, 2);
INSERT INTO `water_Permission_Role` VALUES (17, 15);
INSERT INTO `water_Permission_Role` VALUES (17, 17);
INSERT INTO `water_Permission_Role` VALUES (17, 18);
INSERT INTO `water_Permission_Role` VALUES (17, 19);
INSERT INTO `water_Permission_Role` VALUES (18, 1);
INSERT INTO `water_Permission_Role` VALUES (18, 2);
INSERT INTO `water_Permission_Role` VALUES (18, 14);
INSERT INTO `water_Permission_Role` VALUES (18, 15);
INSERT INTO `water_Permission_Role` VALUES (18, 17);
INSERT INTO `water_Permission_Role` VALUES (18, 18);
INSERT INTO `water_Permission_Role` VALUES (18, 19);
INSERT INTO `water_Permission_Role` VALUES (19, 1);
INSERT INTO `water_Permission_Role` VALUES (19, 17);
INSERT INTO `water_Permission_Role` VALUES (19, 18);
INSERT INTO `water_Permission_Role` VALUES (19, 19);
INSERT INTO `water_Permission_Role` VALUES (20, 1);
INSERT INTO `water_Permission_Role` VALUES (20, 2);
INSERT INTO `water_Permission_Role` VALUES (20, 14);
INSERT INTO `water_Permission_Role` VALUES (20, 15);
INSERT INTO `water_Permission_Role` VALUES (20, 17);
INSERT INTO `water_Permission_Role` VALUES (20, 18);
INSERT INTO `water_Permission_Role` VALUES (20, 19);
INSERT INTO `water_Permission_Role` VALUES (21, 1);
INSERT INTO `water_Permission_Role` VALUES (21, 2);
INSERT INTO `water_Permission_Role` VALUES (21, 14);
INSERT INTO `water_Permission_Role` VALUES (21, 15);
INSERT INTO `water_Permission_Role` VALUES (21, 17);
INSERT INTO `water_Permission_Role` VALUES (21, 18);
INSERT INTO `water_Permission_Role` VALUES (21, 19);
INSERT INTO `water_Permission_Role` VALUES (22, 1);
INSERT INTO `water_Permission_Role` VALUES (22, 2);
INSERT INTO `water_Permission_Role` VALUES (22, 14);
INSERT INTO `water_Permission_Role` VALUES (22, 15);
INSERT INTO `water_Permission_Role` VALUES (22, 17);
INSERT INTO `water_Permission_Role` VALUES (22, 18);
INSERT INTO `water_Permission_Role` VALUES (22, 19);
INSERT INTO `water_Permission_Role` VALUES (23, 1);
INSERT INTO `water_Permission_Role` VALUES (23, 2);
INSERT INTO `water_Permission_Role` VALUES (23, 14);
INSERT INTO `water_Permission_Role` VALUES (23, 15);
INSERT INTO `water_Permission_Role` VALUES (23, 17);
INSERT INTO `water_Permission_Role` VALUES (23, 18);
INSERT INTO `water_Permission_Role` VALUES (23, 19);
INSERT INTO `water_Permission_Role` VALUES (24, 1);
INSERT INTO `water_Permission_Role` VALUES (24, 2);
INSERT INTO `water_Permission_Role` VALUES (24, 15);
INSERT INTO `water_Permission_Role` VALUES (24, 17);
INSERT INTO `water_Permission_Role` VALUES (24, 18);
INSERT INTO `water_Permission_Role` VALUES (24, 19);
INSERT INTO `water_Permission_Role` VALUES (25, 1);
INSERT INTO `water_Permission_Role` VALUES (25, 2);
INSERT INTO `water_Permission_Role` VALUES (25, 15);
INSERT INTO `water_Permission_Role` VALUES (25, 17);
INSERT INTO `water_Permission_Role` VALUES (25, 18);
INSERT INTO `water_Permission_Role` VALUES (25, 19);
INSERT INTO `water_Permission_Role` VALUES (26, 1);
INSERT INTO `water_Permission_Role` VALUES (26, 2);
INSERT INTO `water_Permission_Role` VALUES (26, 13);
INSERT INTO `water_Permission_Role` VALUES (26, 14);
INSERT INTO `water_Permission_Role` VALUES (26, 17);
INSERT INTO `water_Permission_Role` VALUES (26, 18);
INSERT INTO `water_Permission_Role` VALUES (26, 19);
INSERT INTO `water_Permission_Role` VALUES (27, 1);
INSERT INTO `water_Permission_Role` VALUES (27, 2);
INSERT INTO `water_Permission_Role` VALUES (27, 17);
INSERT INTO `water_Permission_Role` VALUES (27, 18);
INSERT INTO `water_Permission_Role` VALUES (27, 19);
INSERT INTO `water_Permission_Role` VALUES (28, 1);
INSERT INTO `water_Permission_Role` VALUES (28, 2);
INSERT INTO `water_Permission_Role` VALUES (28, 14);
INSERT INTO `water_Permission_Role` VALUES (28, 17);
INSERT INTO `water_Permission_Role` VALUES (28, 18);
INSERT INTO `water_Permission_Role` VALUES (28, 19);
INSERT INTO `water_Permission_Role` VALUES (29, 1);
INSERT INTO `water_Permission_Role` VALUES (29, 2);
INSERT INTO `water_Permission_Role` VALUES (29, 13);
INSERT INTO `water_Permission_Role` VALUES (29, 17);
INSERT INTO `water_Permission_Role` VALUES (29, 19);
INSERT INTO `water_Permission_Role` VALUES (30, 1);
INSERT INTO `water_Permission_Role` VALUES (30, 2);
INSERT INTO `water_Permission_Role` VALUES (30, 13);
INSERT INTO `water_Permission_Role` VALUES (30, 14);
INSERT INTO `water_Permission_Role` VALUES (30, 19);
INSERT INTO `water_Permission_Role` VALUES (31, 1);
INSERT INTO `water_Permission_Role` VALUES (31, 2);
INSERT INTO `water_Permission_Role` VALUES (31, 13);
INSERT INTO `water_Permission_Role` VALUES (31, 14);
INSERT INTO `water_Permission_Role` VALUES (31, 19);
INSERT INTO `water_Permission_Role` VALUES (32, 1);
INSERT INTO `water_Permission_Role` VALUES (32, 19);
INSERT INTO `water_Permission_Role` VALUES (33, 1);
INSERT INTO `water_Permission_Role` VALUES (33, 2);
INSERT INTO `water_Permission_Role` VALUES (33, 13);
INSERT INTO `water_Permission_Role` VALUES (33, 14);
INSERT INTO `water_Permission_Role` VALUES (33, 19);
INSERT INTO `water_Permission_Role` VALUES (34, 1);
INSERT INTO `water_Permission_Role` VALUES (34, 2);
INSERT INTO `water_Permission_Role` VALUES (34, 13);
INSERT INTO `water_Permission_Role` VALUES (34, 14);
INSERT INTO `water_Permission_Role` VALUES (35, 1);
INSERT INTO `water_Permission_Role` VALUES (35, 2);
INSERT INTO `water_Permission_Role` VALUES (35, 13);

# INSERT INTO `water_role_user` VALUES (1,1);
# INSERT INTO `water_role_user` VALUES (14,2);


INSERT INTO `water_MenuCate` VALUES (1,  '保护管理', 2  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (3,  '履职尽责', 3  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (4,  '问题整治', 5  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (5,  '社会力量', 6  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (7,  '系统配置', 9  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (8,  '考核问责', 8  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (9,  '组织体系', 1  ,1,null,"");
INSERT INTO `water_MenuCate` VALUES (12, '日志管理', 11 ,1,null,"");